#!/usr/bin/env bash

# ---
# IMPORTANT: Use the following statement at the TOP OF EVERY TEST SCRIPT
#            to ensure that this package's 'bin/' subfolder is added to the path so that
#            this package's CLIs can be invoked by their mere filename in the rest
#            of the script.
# ---
PATH=${PWD%%/test*}/bin:$PATH

# Helper function for error reporting.
die() { (( $# > 0 )) && echo "ERROR: $*" >&2; exit 1; }


thisDir=./$(basename "$(cd "$(dirname "$0")"; basename "$PWD")")
thisFile=$thisDir/$(basename "$0")

cat <<EOF >&2
MISSING TESTS

Please add tests to this directory ($thisDir), then delete or rename and
repurpose this file ($thisFile).

- If your package implements a CLI only:
  Tests are expected to be *shell scripts* run by *Urchin*;
  see https://github.com/tlevine/urchin
  Tests for standard CLI options -h/--help and --version
  were added.

- If your package (also) implements a JS module:
  Tests are run with *tap*, and can either be shell scripts
  or *.js files - see https://www.npmjs.com/package/tap
  A sample tap test was added.

(To make do without tests, simply remove all content from $thisDir)
EOF

exit 2
