#!/usr/bin/env bash

# Source the shared constants.
# Defines BUNDLE_ID, KEYWORD, CACHEFILE_FILTER, CACHEFILE_LASTVSPEC, CACHEFILE_LASTQUERY, CACHEFILE_TEXT, ...
. shared/constants || exit

./voices -d "$*" 2>&1

# REDISPLAY Alfred, so the user can continue to experiment.
./redisplay
