#!/usr/bin/env osascript -l AppleScript

# Opens System Preferences > Dictation & Speech > TTS to allow
# the user to manage (the set of active) voices.
tell application "System Preferences"
      reveal pane id "com.apple.preference.speech"
      tell pane id "com.apple.preference.speech"
           reveal anchor "TTS"
      end tell
      activate
end tell
