#!/usr/bin/env bash

# Source the shared constants.
# Defines BUNDLE_ID, KEYWORD, CACHEFILE_FILTER, CACHEFILE_LASTVSPEC, CACHEFILE_LASTQUERY, CACHEFILE_TEXT, ...
. shared/constants || exit

# --- BEGIN: Helper functions

# Redisplays Alfred with the same query as before, so the user can continue to experiment.
redisplay() {
  local lastQuery=$(<"$CACHEFILE_LASTQUERY")
  osascript -e 'tell application "Alfred 2" to search "'"${KEYWORD}${lastQuery//\"/\\\"}"'"'
}

# --- END: Helper functions

redisplay
